# Change these first
owner: iliksis # Your GitHub organization or username, where this repository lives
repo: status.iliksis.com # The name of this repository

sites:
  - name: TT Hub
    url: https://tthub.iliksis.com
  - name: D2 BountyTracker
    url: https://d2bountytracker.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  cname: status.iliksis.com
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #baseUrl: /$REPO
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
